general {
    hide_cursor = true
    grace = 0
    disable_loading_bar = true
}

background {
    monitor =
    color = rgba(18, 18, 18, 1.0)
}

input-field {
    size = 200, 50
    outline_thickness = 2
    outer_color = rgba(240, 240, 240, 1.0)
    inner_color = rgba(18, 18, 18, 1.0)
    font_color = rgba(240, 240, 240, 1.0)
    font_family = JetBrains Mono
    placeholder_text = Password...
    fail_text = Wrong password
    fail_transition_ms = 300
}

label {
    text = $TIME
    color = rgba(240, 240, 240, 1.0)
    font_size = 64
    font_family = JetBrains Mono
    position = 0, -20
    halign = center
    valign = center
}
